### ISSUE TITLE
Makes Logo as Link

### ISSUE THREAD

**Issue by f1lander** [ObolNetwork/obol-site#29]
## description
Enable the logo as a link that got to the main site.

<img width="997" alt="image" src="https://user-images.githubusercontent.com/5679878/182690395-64250f7c-6f2b-4c5e-9cf8-6cfd5e0de2a1.png">

**Comment by thomasheremans** [comment]
Hey @f1lander , could you please size this as you moved it to this sprint but we didn't size it together. Thanks
