### ISSUE TITLE
Update Ecosystem with remaining tabs 

### ISSUE THREAD

**Issue by Battenfield** [ObolNetwork/obol-site#36]
## Problem to be Solved

Collect the contend and create the additional tabs including:

- Network Validators
- Network Contributors
- Backers
- Advisors
- Core Team (any new members)

<img width="668" alt="Screen Shot 2022-08-31 at 12 46 17 AM" src="https://user-images.githubusercontent.com/7051522/187622247-26e12326-7967-4913-b966-9bd0b7dc95f3.png">

**Comment by thomasheremans** [comment]
@Battenfield can you share the data with @HananINouman

**Comment by thomasheremans** [comment]
Check with Brett/Richard
