### ISSUE TITLE
Update Launchpad link

### ISSUE THREAD

**Issue by Battenfield** [ObolNetwork/obol-site#56]
## Problem to be solved

Update the launchpad link to say "Launch" and link out to `https://goerli.launchpad.obol.tech`

**Comment by Battenfield** [comment]
For reference:

<img width="742" alt="Screen Shot 2022-12-02 at 8 48 42 PM" src="https://user-images.githubusercontent.com/7051522/205424122-c80ca1f1-937a-4b83-9dc8-2ddcacd8df1b.png">

**Comment by f1lander** [comment]
> ## Problem to be solved
> Update the launchpad link to say "Launch" and link out to `https://goerli.launchpad.obol.tech`

What about Launch on Goerli ?

<img width="858" alt="image" src="https://user-images.githubusercontent.com/5679878/205425152-459bcb42-e1ed-454d-ac50-ca948887bafd.png">

**Comment by Battenfield** [comment]
perfect!
