### ISSUE TITLE
Add our illustrations to our brand kit

### ISSUE THREAD

**Issue by OisinKyne** [ObolNetwork/obol-site#58]
## Problem to be solved

We have nice brand assets we should use as much as possible. Not everyone has access to the source files.  

## Proposed solution

Put them on our branding page https://blog.obol.tech/branding/ or link to them from there and put them on a page of their own in ghost. 

Ask oisin and brett for links to assets as we have many variants and resolutions and backgrounds most likely to compile into a clean and complete list

**Comment by Composeus** [comment]
https://blog.obol.tech/branding/ core 6 illustrations added.

**Comment by OisinKyne** [comment]
TYVM brett!
