### ISSUE TITLE
Update Obol Roadmap Graphic on Website Main Page

### ISSUE THREAD

**Issue by Composeus** [ObolNetwork/obol-site#72]
# 🎯 Problem to be solved

As we announce an updated Road to Mainnet on Wednesday we need to update the graphic on the website to reflect the latest stages we are communicating.

# 🛠️ Proposed solution

We will keep the graphic style used in the current website and add additional "planets" to reflect the new stages we've specified. We will implement a larger planet for launches and smaller planet for testnets.

The stages will be as follows:
* Devnets (Small)
* Athena Testnet (Small)
* First Mainnet DV (Large)
* Bia Testnet (Small)
* Alpha Launch (Large)
* Circe Attack Net (Small)
* Beta Launch (Large)
* Demeter Testnet (Small)
* Public Launch (Large)

Additional color gradients:
* B6EA5C --> FFFA81
* 3FF9F9 --> EDEDED
* 9167E4 --> 3E85BD
* 001AFF --> 3EBD9F

Due Date: Wednesday Feb 22 (timing with the launch of the Road to Mainnet blog)

NOTE: Tooltip text to follow in a comment.

**Comment by Composeus** [comment]
Here's proposed tooltip text about details for each of these stages. @OisinKyne @Battenfield this definitely needs your eyes to make sure we've described the main points in each stage correctly. Thanks!

* Devnets -- unchanged
* Athena Testnet
   - Engage Obol Community
   - Public creation of DVs
   - Measure the performance of DVs created by at-home validators
* First Mainnet DV
   - Deployed by Obol Core Team
   - Test the performance of DV on Mainnet
* Bia Testnet
   - Scale public creation of DVs
   - Facilitate self-service through DV Launchpad
   - Stress test Charon middleware in different conditions
* Alpha Launch
   - Guarded Mainnet launch with small group of validators
   - Close support to ensure successful deployments
* Circe Attack Net
   - Discover and fix any potential vulnerabilities
   - Break Charon in multiple ways
   - Improve DoS resistance
* Beta Launch
   - Guarded launch with a larger group of validators under a business license
   - Allow access to a wider audience in a controlled manner
   - Enable predominantly self-service deployments
* Demeter Testnet
   - Final testnet prior to public launch
   - Simulate full Mainnet deployment and address any final issues
* Public Launch
   - Full public launch of V1 to all validators

**Comment by f1lander** [comment]
I created these options, for the original one (option #1) I guess we should remove the checkmarks due the number of planets, will overload the art with more circles so we can represent it as completed leaving the line green and the dotted line for uncompleted

![Image](https://user-images.githubusercontent.com/5679878/220251432-fbbddb15-7fd2-4877-a5c5-96c6f34c3eb7.png)

Let me know what you think @Composeus @OisinKyne

**Comment by Composeus** [comment]
I think we should stick w/ option 1 right now for simplicity sake. Only thin I wonder if we can do is to make the line a bit more curved rather than straight.

**Comment by f1lander** [comment]
Ok, I was trying to do that but I don't know how to it unfortunately

**Comment by f1lander** [comment]
Option #2 enhanced 

![image](https://user-images.githubusercontent.com/5679878/220416703-3b04a564-8e4d-413a-a5f6-76e5cbec369a.png)

**Comment by f1lander** [comment]
Alternative, colors to represent status



![Image](https://user-images.githubusercontent.com/5679878/220426599-992d95c6-d285-4190-a750-f138e8c9e62e.png)

**Comment by f1lander** [comment]
Closing this but wait for the final decision.
