### ISSUE TITLE
add Kukis Global to our list of backers

### ISSUE THREAD

**Issue by boulder225** [ObolNetwork/obol-site#90]
**🎯 Problem to be solved:**
We forgot to add Kukis Global (https://www.kukis-global.com/) to our list of backers on our website https://obol.tech/. This omission has resulted in the absence of acknowledgement for their support, potentially hurting their relationship with our platform.

**🛠️ Proposed solution:**
To rectify this oversight, we should immediately update the list of backers on the website https://obol.tech/ to include Kukis Global (https://www.kukis-global.com/). 
![image.png](https://images.zenhubusercontent.com/648c138feb5dc8a72ad3911a/2ab58cff-c994-4c06-b57c-727afdc602fc)

**Comment by boulder225** [comment]
![Kukis Global Logo](https://github.com/ObolNetwork/obol-site/assets/68026093/2a486411-8115-4b66-87f1-3be68279a7f0)
![Kukis Global Logo](https://github.com/ObolNetwork/obol-site/assets/68026093/06983fa1-4207-4522-844e-f5c7a300f46e)

**Comment by f1lander** [comment]
@boulder225 do we have the file logo?

**Comment by f1lander** [comment]
Added here, https://github.com/ObolNetwork/obol-site/pull/91
